---
BaseURL: "http://kounoike.github.io/"
Title: "Kounoike's GitHub Pages"
MetaDataFormat: yaml
languagecode: "ja-jp"
theme: hugo-redlounge
author:
  name: "KOUNOIKE Yuusuke"
  email: "kounoike.yuusuke@gmail.com"
  github: "kounoike"
  twitter: "ko_noike"
permalinks:
  post: /:year/:month/:day/:title 
blackfriday:
  plainIdAnchors: true
params:
  sidebartitle: "こーのいけのGitHub Page"
  Description: "GitHub Pageがしたい！"
  highlight_theme: "solarized_light"
  notoc: false
  authortwitter: ko_noike
  highlightStyle: solarized_light
menu:
  main: 
    - name: "Blog"
      url: "/posts"
    - name: "Pages"
      url: "/links"
  social:
    - pre: "<i class='fa fa-twitter'></i>"
      url: "http://www.twitter.com/ko_noike"
      identifier: "twitter"
    - pre: "<i class='fa fa-github'></i>"
      url: "https://github.com/kounoike"
      identfier: "github"
